package de.pxav.kelp.core.inventory.material;

import de.pxav.kelp.core.version.KelpVersion;

import java.util.ArrayList;
import java.util.Collection;

/**
 * This enum represents all materials you can use when writing a
 * kelp application. Note that you can only use materials which
 * are available in your minimum server version.
 *
 * @author pxav
 */
public enum KelpMaterial {

  // BANNERS
  BLACK_BANNER(KelpVersion.MC_1_8_0),
  BLUE_BANNER(KelpVersion.MC_1_8_0),
  BROWN_BANNER(KelpVersion.MC_1_8_0),
  CYAN_BANNER(KelpVersion.MC_1_8_0),
  GRAY_BANNER(KelpVersion.MC_1_8_0),
  GREEN_BANNER(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_BANNER(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_BANNER(KelpVersion.MC_1_8_0),
  LIME_BANNER(KelpVersion.MC_1_8_0),
  MAGENTA_BANNER(KelpVersion.MC_1_8_0),
  ORANGE_BANNER(KelpVersion.MC_1_8_0),
  PINK_BANNER(KelpVersion.MC_1_8_0),
  PURPLE_BANNER(KelpVersion.MC_1_8_0),
  RED_BANNER(KelpVersion.MC_1_8_0),
  WHITE_BANNER(KelpVersion.MC_1_8_0),
  YELLOW_BANNER(KelpVersion.MC_1_8_0),

  // BANNER ITEMS
  BLACK_BANNER_ITEM(KelpVersion.MC_1_8_0),
  BLUE_BANNER_ITEM(KelpVersion.MC_1_8_0),
  BROWN_BANNER_ITEM(KelpVersion.MC_1_8_0),
  CYAN_BANNER_ITEM(KelpVersion.MC_1_8_0),
  GRAY_BANNER_ITEM(KelpVersion.MC_1_8_0),
  GREEN_BANNER_ITEM(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_BANNER_ITEM(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_BANNER_ITEM(KelpVersion.MC_1_8_0),
  LIME_BANNER_ITEM(KelpVersion.MC_1_8_0),
  MAGENTA_BANNER_ITEM(KelpVersion.MC_1_8_0),
  ORANGE_BANNER_ITEM(KelpVersion.MC_1_8_0),
  PINK_BANNER_ITEM(KelpVersion.MC_1_8_0),
  PURPLE_BANNER_ITEM(KelpVersion.MC_1_8_0),
  RED_BANNER_ITEM(KelpVersion.MC_1_8_0),
  WHITE_BANNER_ITEM(KelpVersion.MC_1_8_0),
  YELLOW_BANNER_ITEM(KelpVersion.MC_1_8_0),

  // BANNER PATTERNS
  FLOWER_BANNER_PATTERN(KelpVersion.MC_1_14_0),
  GLOBE_BANNER_PATTERN(KelpVersion.MC_1_14_0),
  CREEPER_BANNER_PATTERN(KelpVersion.MC_1_14_0),
  MOJANG_BANNER_PATTERN(KelpVersion.MC_1_14_0),
  SKULL_BANNER_PATTERN(KelpVersion.MC_1_14_0),

  // WALL BANNERS
  BLACK_WALL_BANNER(KelpVersion.MC_1_8_0),
  BLUE_WALL_BANNER(KelpVersion.MC_1_8_0),
  BROWN_WALL_BANNER(KelpVersion.MC_1_8_0),
  CYAN_WALL_BANNER(KelpVersion.MC_1_8_0),
  GRAY_WALL_BANNER(KelpVersion.MC_1_8_0),
  GREEN_WALL_BANNER(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_WALL_BANNER(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_WALL_BANNER(KelpVersion.MC_1_8_0),
  LIME_WALL_BANNER(KelpVersion.MC_1_8_0),
  MAGENTA_WALL_BANNER(KelpVersion.MC_1_8_0),
  ORANGE_WALL_BANNER(KelpVersion.MC_1_8_0),
  PINK_WALL_BANNER(KelpVersion.MC_1_8_0),
  PURPLE_WALL_BANNER(KelpVersion.MC_1_8_0),
  RED_WALL_BANNER(KelpVersion.MC_1_8_0),
  WHITE_WALL_BANNER(KelpVersion.MC_1_8_0),
  YELLOW_WALL_BANNER(KelpVersion.MC_1_8_0),

  // BOATS
  ACACIA_BOAT(KelpVersion.MC_1_9_0),
  BIRCH_BOAT(KelpVersion.MC_1_9_0),
  DARK_OAK_BOAT(KelpVersion.MC_1_9_0),
  JUNGLE_BOAT(KelpVersion.MC_1_9_0),
  OAK_BOAT(KelpVersion.MC_1_8_0),
  SPRUCE_BOAT(KelpVersion.MC_1_9_0),

  // BUTTONS
  ACACIA_BUTTON(KelpVersion.MC_1_13_0),
  BIRCH_BUTTON(KelpVersion.MC_1_13_0),
  DARK_OAK_BUTTON(KelpVersion.MC_1_13_0),
  JUNGLE_BUTTON(KelpVersion.MC_1_13_0),
  OAK_BUTTON(KelpVersion.MC_1_13_0),
  SPRUCE_BUTTON(KelpVersion.MC_1_13_0),
  STONE_BUTTON(KelpVersion.MC_1_13_0),

  // HARDENED CLAY / TERRACOTTA
  BLACK_TERRACOTTA(KelpVersion.MC_1_8_0),
  BLUE_TERRACOTTA(KelpVersion.MC_1_8_0),
  BROWN_TERRACOTTA(KelpVersion.MC_1_8_0),
  CYAN_TERRACOTTA(KelpVersion.MC_1_8_0),
  GRAY_TERRACOTTA(KelpVersion.MC_1_8_0),
  GREEN_TERRACOTTA(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_TERRACOTTA(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_TERRACOTTA(KelpVersion.MC_1_8_0),
  LIME_TERRACOTTA(KelpVersion.MC_1_8_0),
  MAGENTA_TERRACOTTA(KelpVersion.MC_1_8_0),
  ORANGE_TERRACOTTA(KelpVersion.MC_1_8_0),
  PINK_TERRACOTTA(KelpVersion.MC_1_8_0),
  PURPLE_TERRACOTTA(KelpVersion.MC_1_8_0),
  RED_TERRACOTTA(KelpVersion.MC_1_8_0),
  TERRACOTTA(KelpVersion.MC_1_8_0),
  WHITE_TERRACOTTA(KelpVersion.MC_1_8_0),
  YELLOW_TERRACOTTA(KelpVersion.MC_1_8_0),

  // GLAZED TERRACOTTA
  BLACK_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  BLUE_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  BROWN_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  CYAN_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  GRAY_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  GREEN_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  LIGHT_BLUE_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  LIGHT_GRAY_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  LIME_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  MAGENTA_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  ORANGE_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  PINK_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  PURPLE_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  RED_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  WHITE_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),
  YELLOW_GLAZED_TERRACOTTA(KelpVersion.MC_1_12_0),

  // DOORS
  ACACIA_DOOR(KelpVersion.MC_1_8_0),
  BIRCH_DOOR(KelpVersion.MC_1_8_0),
  DARK_OAK_DOOR(KelpVersion.MC_1_8_0),
  IRON_DOOR(KelpVersion.MC_1_8_0),
  JUNGLE_DOOR(KelpVersion.MC_1_8_0),
  OAK_DOOR(KelpVersion.MC_1_8_0),
  SPRUCE_DOOR(KelpVersion.MC_1_8_0),

  // FENCES
  ACACIA_FENCE(KelpVersion.MC_1_8_0),
  BIRCH_FENCE(KelpVersion.MC_1_8_0),
  DARK_OAK_FENCE(KelpVersion.MC_1_8_0),
  JUNGLE_FENCE(KelpVersion.MC_1_8_0),
  OAK_FENCE(KelpVersion.MC_1_8_0),
  SPRUCE_FENCE(KelpVersion.MC_1_8_0),
  NETHER_BRICK_FENCE(KelpVersion.MC_1_8_0),

  // FENCE GATES
  ACACIA_FENCE_GATE(KelpVersion.MC_1_8_0),
  BIRCH_FENCE_GATE(KelpVersion.MC_1_8_0),
  DARK_OAK_FENCE_GATE(KelpVersion.MC_1_8_0),
  JUNGLE_FENCE_GATE(KelpVersion.MC_1_8_0),
  OAK_FENCE_GATE(KelpVersion.MC_1_8_0),
  SPRUCE_FENCE_GATE(KelpVersion.MC_1_8_0),

  // LEAVES
  ACACIA_LEAVES(KelpVersion.MC_1_8_0),
  BIRCH_LEAVES(KelpVersion.MC_1_8_0),
  DARK_OAK_LEAVES(KelpVersion.MC_1_8_0),
  JUNGLE_LEAVES(KelpVersion.MC_1_8_0),
  OAK_LEAVES(KelpVersion.MC_1_8_0),
  SPRUCE_LEAVES(KelpVersion.MC_1_8_0),

  // STRIPPED LOGS
  STRIPPED_ACACIA_LOG(KelpVersion.MC_1_13_0),
  STRIPPED_BIRCH_LOG(KelpVersion.MC_1_13_0),
  STRIPPED_DARK_OAK_LOG(KelpVersion.MC_1_13_0),
  STRIPPED_JUNGLE_LOG(KelpVersion.MC_1_13_0),
  STRIPPED_OAK_LOG(KelpVersion.MC_1_13_0),
  STRIPPED_SPRUCE_LOG(KelpVersion.MC_1_13_0),

  // LOGS
  ACACIA_LOG(KelpVersion.MC_1_8_0),
  BIRCH_LOG(KelpVersion.MC_1_8_0),
  DARK_OAK_LOG(KelpVersion.MC_1_8_0),
  JUNGLE_LOG(KelpVersion.MC_1_8_0),
  OAK_LOG(KelpVersion.MC_1_8_0),
  SPRUCE_LOG(KelpVersion.MC_1_8_0),

  // STRIPPED WOOD
  STRIPPED_ACACIA_WOOD(KelpVersion.MC_1_13_0),
  STRIPPED_BIRCH_WOOD(KelpVersion.MC_1_13_0),
  STRIPPED_DARK_OAK_WOOD(KelpVersion.MC_1_13_0),
  STRIPPED_JUNGLE_WOOD(KelpVersion.MC_1_13_0),
  STRIPPED_OAK_WOOD(KelpVersion.MC_1_13_0),
  STRIPPED_SPRUCE_WOOD(KelpVersion.MC_1_13_0),

  // PLANKS
  ACACIA_PLANKS(KelpVersion.MC_1_8_0),
  BIRCH_PLANKS(KelpVersion.MC_1_8_0),
  DARK_OAK_PLANKS(KelpVersion.MC_1_8_0),
  JUNGLE_PLANKS(KelpVersion.MC_1_8_0),
  OAK_PLANKS(KelpVersion.MC_1_8_0),
  SPRUCE_PLANKS(KelpVersion.MC_1_8_0),

  // CONCRETE POWDER
  BLACK_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  BLUE_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  BROWN_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  CYAN_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  GRAY_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  GREEN_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  LIGHT_BLUE_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  LIGHT_GRAY_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  LIME_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  MAGENTA_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  ORANGE_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  PINK_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  PURPLE_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  RED_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  WHITE_CONCRETE_POWDER(KelpVersion.MC_1_12_0),
  YELLOW_CONCRETE_POWDER(KelpVersion.MC_1_12_0),

  // CONCRETE
  BLACK_CONCRETE(KelpVersion.MC_1_12_0),
  BLUE_CONCRETE(KelpVersion.MC_1_12_0),
  BROWN_CONCRETE(KelpVersion.MC_1_12_0),
  CYAN_CONCRETE(KelpVersion.MC_1_12_0),
  GRAY_CONCRETE(KelpVersion.MC_1_12_0),
  GREEN_CONCRETE(KelpVersion.MC_1_12_0),
  LIGHT_BLUE_CONCRETE(KelpVersion.MC_1_12_0),
  LIGHT_GRAY_CONCRETE(KelpVersion.MC_1_12_0),
  LIME_CONCRETE(KelpVersion.MC_1_12_0),
  MAGENTA_CONCRETE(KelpVersion.MC_1_12_0),
  ORANGE_CONCRETE(KelpVersion.MC_1_12_0),
  PINK_CONCRETE(KelpVersion.MC_1_12_0),
  PURPLE_CONCRETE(KelpVersion.MC_1_12_0),
  RED_CONCRETE(KelpVersion.MC_1_12_0),
  WHITE_CONCRETE(KelpVersion.MC_1_12_0),
  YELLOW_CONCRETE(KelpVersion.MC_1_12_0),

  // PRESSURE PLATES
  ACACIA_PRESSURE_PLATE(KelpVersion.MC_1_13_0),
  BIRCH_PRESSURE_PLATE(KelpVersion.MC_1_13_0),
  DARK_OAK_PRESSURE_PLATE(KelpVersion.MC_1_13_0),
  HEAVY_WEIGHTED_PRESSURE_PLATE(KelpVersion.MC_1_8_0),
  JUNGLE_PRESSURE_PLATE(KelpVersion.MC_1_13_0),
  LIGHT_WEIGHTED_PRESSURE_PLATE(KelpVersion.MC_1_8_0),
  OAK_PRESSURE_PLATE(KelpVersion.MC_1_8_0),
  SPRUCE_PRESSURE_PLATE(KelpVersion.MC_1_13_0),
  STONE_PRESSURE_PLATE(KelpVersion.MC_1_8_0),

  // SAPLINGS
  ACACIA_SAPLING(KelpVersion.MC_1_8_0),
  BAMBOO_SAPLING(KelpVersion.MC_1_14_0),
  BIRCH_SAPLING(KelpVersion.MC_1_8_0),
  DARK_OAK_SAPLING(KelpVersion.MC_1_8_0),
  JUNGLE_SAPLING(KelpVersion.MC_1_8_0),
  OAK_SAPLING(KelpVersion.MC_1_8_0),
  SPRUCE_SAPLING(KelpVersion.MC_1_8_0),

  // POTTED SAPLING
  POTTED_ACACIA_SAPLING(KelpVersion.MC_1_8_0),
  POTTED_BIRCH_SAPLING(KelpVersion.MC_1_8_0),
  POTTED_DARK_OAK_SAPLING(KelpVersion.MC_1_8_0),
  POTTED_JUNGLE_SAPLING(KelpVersion.MC_1_8_0),
  POTTED_OAK_SAPLING(KelpVersion.MC_1_8_0),
  POTTED_SPRUCE_SAPLING(KelpVersion.MC_1_8_0),

  // SIGNS
  ACACIA_SIGN(KelpVersion.MC_1_14_0),
  BIRCH_SIGN(KelpVersion.MC_1_14_0),
  DARK_OAK_SIGN(KelpVersion.MC_1_14_0),
  JUNGLE_SIGN(KelpVersion.MC_1_14_0),
  OAK_SIGN(KelpVersion.MC_1_8_0),
  SPRUCE_SIGN(KelpVersion.MC_1_14_0),

  // SIGNS
  ACACIA_SIGN_ITEM(KelpVersion.MC_1_14_0),
  BIRCH_SIGN_ITEM(KelpVersion.MC_1_14_0),
  DARK_OAK_SIGN_ITEM(KelpVersion.MC_1_14_0),
  JUNGLE_SIGN_ITEM(KelpVersion.MC_1_14_0),
  OAK_SIGN_ITEM(KelpVersion.MC_1_8_0),
  SPRUCE_SIGN_ITEM(KelpVersion.MC_1_14_0),

  // WALL SIGNS
  ACACIA_WALL_SIGN(KelpVersion.MC_1_14_0),
  BIRCH_WALL_SIGN(KelpVersion.MC_1_14_0),
  DARK_OAK_WALL_SIGN(KelpVersion.MC_1_14_0),
  JUNGLE_WALL_SIGN(KelpVersion.MC_1_14_0),
  OAK_WALL_SIGN(KelpVersion.MC_1_8_0),
  SPRUCE_WALL_SIGN(KelpVersion.MC_1_14_0),

  // SLABS
  ACACIA_SLAB(KelpVersion.MC_1_8_0),
  ANDESITE_SLAB(KelpVersion.MC_1_14_0),
  BIRCH_SLAB(KelpVersion.MC_1_8_0),
  BRICK_SLAB(KelpVersion.MC_1_8_0),
  COBBLESTONE_SLAB(KelpVersion.MC_1_8_0),
  CUT_RED_SANDSTONE_SLAB(KelpVersion.MC_1_14_0),
  CUT_SANDSTONE_SLAB(KelpVersion.MC_1_14_0),
  DARK_OAK_SLAB(KelpVersion.MC_1_8_0),
  DARK_PRISMARINE_SLAB(KelpVersion.MC_1_13_0),
  DIORITE_SLAB(KelpVersion.MC_1_14_0),
  END_STONE_BRICK_SLAB(KelpVersion.MC_1_14_0),
  GRANITE_SLAB(KelpVersion.MC_1_14_0),
  JUNGLE_SLAB(KelpVersion.MC_1_8_0),
  MOSSY_COBBLESTONE_SLAB(KelpVersion.MC_1_14_0),
  MOSSY_STONE_BRICK_SLAB(KelpVersion.MC_1_14_0),
  NETHER_BRICK_SLAB(KelpVersion.MC_1_8_0),
  OAK_SLAB(KelpVersion.MC_1_8_0),
  PETRIFIED_OAK_SLAB(KelpVersion.MC_1_14_0),
  POLISHED_ANDESITE_SLAB(KelpVersion.MC_1_14_0),
  POLISHED_DIORITE_SLAB(KelpVersion.MC_1_14_0),
  POLISHED_GRANITE_SLAB(KelpVersion.MC_1_14_0),
  PRISMARINE_BRICK_SLAB(KelpVersion.MC_1_13_0),
  PRISMARINE_SLAB(KelpVersion.MC_1_13_0),
  PURPUR_SLAB(KelpVersion.MC_1_11_0),
  QUARTZ_SLAB(KelpVersion.MC_1_8_0),
  RED_NETHER_BRICK_SLAB(KelpVersion.MC_1_14_0),
  RED_SANDSTONE_SLAB(KelpVersion.MC_1_8_0),
  SANDSTONE_SLAB(KelpVersion.MC_1_8_0),
  SMOOTH_QUARTZ_SLAB(KelpVersion.MC_1_14_0),
  SMOOTH_RED_SANDSTONE_SLAB(KelpVersion.MC_1_14_0),
  SMOOTH_SANDSTONE_SLAB(KelpVersion.MC_1_14_0),
  SMOOTH_STONE_SLAB(KelpVersion.MC_1_14_0),
  SPRUCE_SLAB(KelpVersion.MC_1_8_0),
  STONE_BRICK_SLAB(KelpVersion.MC_1_8_0),
  STONE_SLAB(KelpVersion.MC_1_8_0),

  // STAIRS
  ACACIA_STAIRS(KelpVersion.MC_1_8_0),
  ANDESITE_STAIRS(KelpVersion.MC_1_14_0),
  BIRCH_STAIRS(KelpVersion.MC_1_8_0),
  BRICK_STAIRS(KelpVersion.MC_1_8_0),
  COBBLESTONE_STAIRS(KelpVersion.MC_1_8_0),
  DARK_OAK_STAIRS(KelpVersion.MC_1_8_0),
  DARK_PRISMARINE_STAIRS(KelpVersion.MC_1_13_0),
  DIORITE_STAIRS(KelpVersion.MC_1_14_0),
  END_STONE_BRICK_STAIRS(KelpVersion.MC_1_14_0),
  GRANITE_STAIRS(KelpVersion.MC_1_14_0),
  JUNGLE_STAIRS(KelpVersion.MC_1_8_0),
  MOSSY_COBBLESTONE_STAIRS(KelpVersion.MC_1_14_0),
  MOSSY_STONE_BRICK_STAIRS(KelpVersion.MC_1_14_0),
  NETHER_BRICK_STAIRS(KelpVersion.MC_1_8_0),
  OAK_STAIRS(KelpVersion.MC_1_8_0),
  POLISHED_ANDESITE_STAIRS(KelpVersion.MC_1_14_0),
  POLISHED_DIORITE_STAIRS(KelpVersion.MC_1_14_0),
  POLISHED_GRANITE_STAIRS(KelpVersion.MC_1_14_0),
  PRISMARINE_BRICK_STAIRS(KelpVersion.MC_1_13_0),
  PRISMARINE_STAIRS(KelpVersion.MC_1_13_0),
  PURPUR_STAIRS(KelpVersion.MC_1_9_0),
  QUARTZ_STAIRS(KelpVersion.MC_1_8_0),
  RED_NETHER_BRICK_STAIRS(KelpVersion.MC_1_14_0),
  RED_SANDSTONE_STAIRS(KelpVersion.MC_1_8_0),
  SANDSTONE_STAIRS(KelpVersion.MC_1_8_0),
  SMOOTH_QUARTZ_STAIRS(KelpVersion.MC_1_14_0),
  SMOOTH_RED_SANDSTONE_STAIRS(KelpVersion.MC_1_14_0),
  SMOOTH_SANDSTONE_STAIRS(KelpVersion.MC_1_14_0),
  SPRUCE_STAIRS(KelpVersion.MC_1_8_0),
  STONE_BRICK_STAIRS(KelpVersion.MC_1_8_0),
  STONE_STAIRS(KelpVersion.MC_1_14_0),

  // TRAPDOORS
  ACACIA_TRAPDOOR(KelpVersion.MC_1_13_0),
  BIRCH_TRAPDOOR(KelpVersion.MC_1_13_0),
  DARK_OAK_TRAPDOOR(KelpVersion.MC_1_13_0),
  IRON_TRAPDOOR(KelpVersion.MC_1_8_0),
  JUNGLE_TRAPDOOR(KelpVersion.MC_1_13_0),
  OAK_TRAPDOOR(KelpVersion.MC_1_8_0),
  SPRUCE_TRAPDOOR(KelpVersion.MC_1_13_0),

  // RAILS
  ACTIVATOR_RAIL(KelpVersion.MC_1_8_0),
  DETECTOR_RAIL(KelpVersion.MC_1_8_0),
  POWERED_RAIL(KelpVersion.MC_1_8_0),
  RAIL(KelpVersion.MC_1_8_0),

  // FLOWERS

  // SPAWN EGGS
  BAT_SPAWN_EGG(KelpVersion.MC_1_8_0),
  BEE_SPAWN_EGG(KelpVersion.MC_1_15_0),
  BLAZE_SPAWN_EGG(KelpVersion.MC_1_8_0),
  CAT_SPAWN_EGG(KelpVersion.MC_1_14_0),
  CAVE_SPIDER_SPAWN_EGG(KelpVersion.MC_1_8_0),
  CHICKEN_SPAWN_EGG(KelpVersion.MC_1_8_0),
  COD_SPAWN_EGG(KelpVersion.MC_1_13_0),
  COW_SPAWN_EGG(KelpVersion.MC_1_8_0),
  CREEPER_SPAWN_EGG(KelpVersion.MC_1_8_0),
  DOLPHIN_SPAWN_EGG(KelpVersion.MC_1_13_0),
  DONKEY_SPAWN_EGG(KelpVersion.MC_1_11_0),
  DROWNED_SPAWN_EGG(KelpVersion.MC_1_13_0),
  ELDER_GUARDIAN_SPAWN_EGG(KelpVersion.MC_1_11_0),
  ENDERMAN_SPAWN_EGG(KelpVersion.MC_1_8_0),
  ENDERMITE_SPAWN_EGG(KelpVersion.MC_1_8_0),
  EVOKER_SPAWN_EGG(KelpVersion.MC_1_11_0),
  FOX_SPAWN_EGG(KelpVersion.MC_1_14_0),
  GHAST_SPAWN_EGG(KelpVersion.MC_1_8_0),
  GUARDIAN_SPAWN_EGG(KelpVersion.MC_1_8_0),
  HORSE_SPAWN_EGG(KelpVersion.MC_1_8_0),
  HUSK_SPAWN_EGG(KelpVersion.MC_1_11_0),
  LLAMA_SPAWN_EGG(KelpVersion.MC_1_11_0),
  MAGMA_CUBE_SPAWN_EGG(KelpVersion.MC_1_8_0),
  MOOSHROOM_SPAWN_EGG(KelpVersion.MC_1_8_0),
  MULE_SPAWN_EGG(KelpVersion.MC_1_11_0),
  OCELOT_SPAWN_EGG(KelpVersion.MC_1_8_0),
  PANDA_SPAWN_EGG(KelpVersion.MC_1_14_0),
  PARROT_SPAWN_EGG(KelpVersion.MC_1_12_0),
  PHANTOM_SPAWN_EGG(KelpVersion.MC_1_13_0),
  PIG_SPAWN_EGG(KelpVersion.MC_1_8_0),
  PILLAGER_SPAWN_EGG(KelpVersion.MC_1_14_0),
  POLAR_BEAR_SPAWN_EGG(KelpVersion.MC_1_11_0),
  PUFFERFISH_SPAWN_EGG(KelpVersion.MC_1_13_0),
  RABBIT_SPAWN_EGG(KelpVersion.MC_1_8_0),
  RAVAGER_SPAWN_EGG(KelpVersion.MC_1_14_0),
  SALMON_SPAWN_EGG(KelpVersion.MC_1_13_0),
  SHEEP_SPAWN_EGG(KelpVersion.MC_1_8_0),
  SHULKER_SPAWN_EGG(KelpVersion.MC_1_9_0),
  SILVERFISH_SPAWN_EGG(KelpVersion.MC_1_8_0),
  SKELETON_HORSE_SPAWN_EGG(KelpVersion.MC_1_11_0),
  SKELETON_SPAWN_EGG(KelpVersion.MC_1_8_0),
  SLIME_SPAWN_EGG(KelpVersion.MC_1_8_0),
  SPIDER_SPAWN_EGG(KelpVersion.MC_1_8_0),
  SQUID_SPAWN_EGG(KelpVersion.MC_1_8_0),
  STRAY_SPAWN_EGG(KelpVersion.MC_1_11_0),
  TRADER_LLAMA_SPAWN_EGG(KelpVersion.MC_1_14_0),
  TROPICAL_FISH_SPAWN_EGG(KelpVersion.MC_1_13_0),
  TURTLE_SPAWN_EGG(KelpVersion.MC_1_13_0),
  VEX_SPAWN_EGG(KelpVersion.MC_1_11_0),
  VILLAGER_SPAWN_EGG(KelpVersion.MC_1_8_0),
  VINDICATOR_SPAWN_EGG(KelpVersion.MC_1_11_0),
  WANDERING_TRADER_SPAWN_EGG(KelpVersion.MC_1_14_0),
  WOLF_SPAWN_EGG(KelpVersion.MC_1_8_0),
  WITCH_SPAWN_EGG(KelpVersion.MC_1_8_0),
  WITHER_SKELETON_SPAWN_EGG(KelpVersion.MC_1_11_0),
  ZOMBIE_HORSE_SPAWN_EGG(KelpVersion.MC_1_11_0),
  ZOMBIE_PIGMAN_SPAWN_EGG(KelpVersion.MC_1_8_0),
  ZOMBIE_SPAWN_EGG(KelpVersion.MC_1_8_0),
  ZOMBIE_VILLAGER_SPAWN_EGG(KelpVersion.MC_1_11_0),

  // SHULKER BOXES
  SHULKER_BOX(KelpVersion.MC_1_11_0),
  BLACK_SHULKER_BOX(KelpVersion.MC_1_11_0),
  BLUE_SHULKER_BOX(KelpVersion.MC_1_11_0),
  BROWN_SHULKER_BOX(KelpVersion.MC_1_11_0),
  CYAN_SHULKER_BOX(KelpVersion.MC_1_11_0),
  GRAY_SHULKER_BOX(KelpVersion.MC_1_11_0),
  GREEN_SHULKER_BOX(KelpVersion.MC_1_11_0),
  LIGHT_BLUE_SHULKER_BOX(KelpVersion.MC_1_11_0),
  LIGHT_GRAY_SHULKER_BOX(KelpVersion.MC_1_11_0),
  LIME_SHULKER_BOX(KelpVersion.MC_1_11_0),
  MAGENTA_SHULKER_BOX(KelpVersion.MC_1_11_0),
  ORANGE_SHULKER_BOX(KelpVersion.MC_1_11_0),
  PINK_SHULKER_BOX(KelpVersion.MC_1_11_0),
  PURPLE_SHULKER_BOX(KelpVersion.MC_1_11_0),
  RED_SHULKER_BOX(KelpVersion.MC_1_11_0),
  WHITE_SHULKER_BOX(KelpVersion.MC_1_11_0),
  YELLOW_SHULKER_BOX(KelpVersion.MC_1_11_0),

  // WALLS
  ANDESITE_WALL(KelpVersion.MC_1_14_0),
  BRICK_WALL(KelpVersion.MC_1_14_0),
  COBBLESTONE_WALL(KelpVersion.MC_1_8_0),
  DIORITE_WALL(KelpVersion.MC_1_14_0),
  END_STONE_BRICK_WALL(KelpVersion.MC_1_14_0),
  GRANITE_WALL(KelpVersion.MC_1_14_0),
  MOSSY_COBBLESTONE_WALL(KelpVersion.MC_1_8_0),
  MOSSY_STONE_BRICK_WALL(KelpVersion.MC_1_14_0),
  NETHER_BRICK_WALL(KelpVersion.MC_1_14_0),
  PRISMARINE_WALL(KelpVersion.MC_1_14_0),
  RED_NETHER_BRICK_WALL(KelpVersion.MC_1_14_0),
  RED_SANDSTONE_WALL(KelpVersion.MC_1_14_0),
  SANDSTONE_WALL(KelpVersion.MC_1_14_0),
  STONE_BRICK_WALL(KelpVersion.MC_1_14_0),

  // WALL SKULLS/HEADS
  CREEPER_WALL_HEAD(KelpVersion.MC_1_8_0),
  DRAGON_WALL_HEAD(KelpVersion.MC_1_9_0),
  PLAYER_WALL_HEAD(KelpVersion.MC_1_8_0),
  SKELETON_WALL_SKULL(KelpVersion.MC_1_8_0),
  WITHER_SKELETON_WALL_SKULL(KelpVersion.MC_1_8_0),
  ZOMBIE_WALL_HEAD(KelpVersion.MC_1_8_0),

  // SKULLS/HEADS
  CREEPER_HEAD(KelpVersion.MC_1_8_0),
  DRAGON_HEAD(KelpVersion.MC_1_9_0),
  PLAYER_HEAD(KelpVersion.MC_1_8_0),
  ZOMBIE_HEAD(KelpVersion.MC_1_8_0),
  SKELETON_SKULL(KelpVersion.MC_1_8_0),
  WITHER_SKELETON_SKULL(KelpVersion.MC_1_8_0),

  // CARPET
  BLACK_CARPET(KelpVersion.MC_1_8_0),
  BLUE_CARPET(KelpVersion.MC_1_8_0),
  BROWN_CARPET(KelpVersion.MC_1_8_0),
  CYAN_CARPET(KelpVersion.MC_1_8_0),
  GRAY_CARPET(KelpVersion.MC_1_8_0),
  GREEN_CARPET(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_CARPET(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_CARPET(KelpVersion.MC_1_8_0),
  LIME_CARPET(KelpVersion.MC_1_8_0),
  MAGENTA_CARPET(KelpVersion.MC_1_8_0),
  ORANGE_CARPET(KelpVersion.MC_1_8_0),
  PINK_CARPET(KelpVersion.MC_1_8_0),
  PURPLE_CARPET(KelpVersion.MC_1_8_0),
  RED_CARPET(KelpVersion.MC_1_8_0),
  WHITE_CARPET(KelpVersion.MC_1_8_0),
  YELLOW_CARPET(KelpVersion.MC_1_8_0),

  // WOOL
  BLACK_WOOL(KelpVersion.MC_1_8_0),
  BLUE_WOOL(KelpVersion.MC_1_8_0),
  BROWN_WOOL(KelpVersion.MC_1_8_0),
  CYAN_WOOL(KelpVersion.MC_1_8_0),
  GRAY_WOOL(KelpVersion.MC_1_8_0),
  GREEN_WOOL(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_WOOL(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_WOOL(KelpVersion.MC_1_8_0),
  LIME_WOOL(KelpVersion.MC_1_8_0),
  MAGENTA_WOOL(KelpVersion.MC_1_8_0),
  ORANGE_WOOL(KelpVersion.MC_1_8_0),
  PINK_WOOL(KelpVersion.MC_1_8_0),
  PURPLE_WOOL(KelpVersion.MC_1_8_0),
  RED_WOOL(KelpVersion.MC_1_8_0),
  WHITE_WOOL(KelpVersion.MC_1_8_0),
  YELLOW_WOOL(KelpVersion.MC_1_8_0),

  // BED
  BLACK_BED(KelpVersion.MC_1_12_0),
  BLUE_BED(KelpVersion.MC_1_12_0),
  BROWN_BED(KelpVersion.MC_1_12_0),
  CYAN_BED(KelpVersion.MC_1_12_0),
  GRAY_BED(KelpVersion.MC_1_12_0),
  GREEN_BED(KelpVersion.MC_1_12_0),
  LIGHT_BLUE_BED(KelpVersion.MC_1_12_0),
  LIGHT_GRAY_BED(KelpVersion.MC_1_12_0),
  LIME_BED(KelpVersion.MC_1_12_0),
  MAGENTA_BED(KelpVersion.MC_1_12_0),
  ORANGE_BED(KelpVersion.MC_1_12_0),
  PINK_BED(KelpVersion.MC_1_12_0),
  PURPLE_BED(KelpVersion.MC_1_12_0),
  RED_BED(KelpVersion.MC_1_8_0),
  WHITE_BED(KelpVersion.MC_1_12_0),
  YELLOW_BED(KelpVersion.MC_1_12_0),

  // DYE
  BLACK_DYE(KelpVersion.MC_1_14_0),
  BLUE_DYE(KelpVersion.MC_1_14_0),
  BROWN_DYE(KelpVersion.MC_1_14_0),
  CYAN_DYE(KelpVersion.MC_1_8_0),
  GRAY_DYE(KelpVersion.MC_1_8_0),
  GREEN_DYE(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_DYE(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_DYE(KelpVersion.MC_1_8_0),
  LIME_DYE(KelpVersion.MC_1_8_0),
  MAGENTA_DYE(KelpVersion.MC_1_8_0),
  ORANGE_DYE(KelpVersion.MC_1_8_0),
  PINK_DYE(KelpVersion.MC_1_8_0),
  PURPLE_DYE(KelpVersion.MC_1_8_0),
  RED_DYE(KelpVersion.MC_1_8_0),
  WHITE_DYE(KelpVersion.MC_1_14_0),
  YELLOW_DYE(KelpVersion.MC_1_8_0),

  // GLASS PANES
  GLASS_PANE(KelpVersion.MC_1_8_0),
  BLACK_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  BLUE_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  BROWN_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  CYAN_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  GRAY_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  GREEN_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  LIME_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  MAGENTA_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  ORANGE_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  PINK_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  PURPLE_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  RED_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  WHITE_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),
  YELLOW_STAINED_GLASS_PANE(KelpVersion.MC_1_8_0),

  // GLASS
  GLASS(KelpVersion.MC_1_8_0),
  BLACK_STAINED_GLASS(KelpVersion.MC_1_8_0),
  BLUE_STAINED_GLASS(KelpVersion.MC_1_8_0),
  BROWN_STAINED_GLASS(KelpVersion.MC_1_8_0),
  CYAN_STAINED_GLASS(KelpVersion.MC_1_8_0),
  GRAY_STAINED_GLASS(KelpVersion.MC_1_8_0),
  GREEN_STAINED_GLASS(KelpVersion.MC_1_8_0),
  LIGHT_BLUE_STAINED_GLASS(KelpVersion.MC_1_8_0),
  LIGHT_GRAY_STAINED_GLASS(KelpVersion.MC_1_8_0),
  LIME_STAINED_GLASS(KelpVersion.MC_1_8_0),
  MAGENTA_STAINED_GLASS(KelpVersion.MC_1_8_0),
  ORANGE_STAINED_GLASS(KelpVersion.MC_1_8_0),
  PINK_STAINED_GLASS(KelpVersion.MC_1_8_0),
  PURPLE_STAINED_GLASS(KelpVersion.MC_1_8_0),
  RED_STAINED_GLASS(KelpVersion.MC_1_8_0),
  WHITE_STAINED_GLASS(KelpVersion.MC_1_8_0),
  YELLOW_STAINED_GLASS(KelpVersion.MC_1_8_0),

  // POTIONS
  LINGERING_POTION(KelpVersion.MC_1_9_0),
  POTION(KelpVersion.MC_1_8_0),
  SPLASH_POTION(KelpVersion.MC_1_8_0),

  // SHOVELS
  DIAMOND_SHOVEL(KelpVersion.MC_1_8_0),
  GOLDEN_SHOVEL(KelpVersion.MC_1_8_0),
  IRON_SHOVEL(KelpVersion.MC_1_8_0),
  STONE_SHOVEL(KelpVersion.MC_1_8_0),
  WOODEN_SHOVEL(KelpVersion.MC_1_8_0),

  // HOES
  DIAMOND_HOE(KelpVersion.MC_1_8_0),
  GOLDEN_HOE(KelpVersion.MC_1_8_0),
  IRON_HOE(KelpVersion.MC_1_8_0),
  STONE_HOE(KelpVersion.MC_1_8_0),
  WOODEN_HOE(KelpVersion.MC_1_8_0),

  // AXES
  DIAMOND_AXE(KelpVersion.MC_1_8_0),
  GOLDEN_AXE(KelpVersion.MC_1_8_0),
  IRON_AXE(KelpVersion.MC_1_8_0),
  STONE_AXE(KelpVersion.MC_1_8_0),
  WOODEN_AXE(KelpVersion.MC_1_8_0),

  // PICKAXE
  DIAMOND_PICKAXE(KelpVersion.MC_1_8_0),
  GOLDEN_PICKAXE(KelpVersion.MC_1_8_0),
  IRON_PICKAXE(KelpVersion.MC_1_8_0),
  STONE_PICKAXE(KelpVersion.MC_1_8_0),
  WOODEN_PICKAXE(KelpVersion.MC_1_8_0),

  // SWORDS
  DIAMOND_SWORD(KelpVersion.MC_1_8_0),
  GOLDEN_SWORD(KelpVersion.MC_1_8_0),
  IRON_SWORD(KelpVersion.MC_1_8_0),
  STONE_SWORD(KelpVersion.MC_1_8_0),
  WOODEN_SWORD(KelpVersion.MC_1_8_0),

  // CORALS
  BRAIN_CORAL(KelpVersion.MC_1_13_0),
  BRAIN_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  BRAIN_CORAL_FAN(KelpVersion.MC_1_13_0),
  BRAIN_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  BUBBLE_CORAL(KelpVersion.MC_1_13_0),
  BUBBLE_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  BUBBLE_CORAL_FAN(KelpVersion.MC_1_13_0),
  BUBBLE_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  DEAD_BRAIN_CORAL(KelpVersion.MC_1_13_0),
  DEAD_BRAIN_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  DEAD_BRAIN_CORAL_FAN(KelpVersion.MC_1_13_0),
  DEAD_BRAIN_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  DEAD_BUBBLE_CORAL(KelpVersion.MC_1_13_0),
  DEAD_BUBBLE_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  DEAD_BUBBLE_CORAL_FAN(KelpVersion.MC_1_13_0),
  DEAD_BUBBLE_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  DEAD_FIRE_CORAL(KelpVersion.MC_1_13_0),
  DEAD_FIRE_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  DEAD_FIRE_CORAL_FAN(KelpVersion.MC_1_13_0),
  DEAD_FIRE_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  DEAD_HORN_CORAL(KelpVersion.MC_1_13_0),
  DEAD_HORN_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  DEAD_HORN_CORAL_FAN(KelpVersion.MC_1_13_0),
  DEAD_HORN_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  DEAD_TUBE_CORAL(KelpVersion.MC_1_13_0),
  DEAD_TUBE_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  DEAD_TUBE_CORAL_FAN(KelpVersion.MC_1_13_0),
  DEAD_TUBE_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  FIRE_CORAL(KelpVersion.MC_1_13_0),
  FIRE_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  FIRE_CORAL_FAN(KelpVersion.MC_1_13_0),
  FIRE_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  HORN_CORAL(KelpVersion.MC_1_13_0),
  HORN_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  HORN_CORAL_FAN(KelpVersion.MC_1_13_0),
  HORN_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),
  TUBE_CORAL(KelpVersion.MC_1_13_0),
  TUBE_CORAL_BLOCK(KelpVersion.MC_1_13_0),
  TUBE_CORAL_FAN(KelpVersion.MC_1_13_0),
  TUBE_CORAL_WALL_FAN(KelpVersion.MC_1_13_0),

  // MELONS
  MELON(KelpVersion.MC_1_8_0),
  MELON_SEEDS(KelpVersion.MC_1_8_0),
  MELON_SLICE(KelpVersion.MC_1_8_0),
  MELON_STEM(KelpVersion.MC_1_8_0),
  ATTACHED_MELON_STEM(KelpVersion.MC_1_8_0),

  // PUMPKINS
  ATTACHED_PUMPKIN_STEM(KelpVersion.MC_1_8_0),
  CARVED_PUMPKIN(KelpVersion.MC_1_8_0),
  PUMPKIN(KelpVersion.MC_1_13_0),
  PUMPKIN_PIE(KelpVersion.MC_1_8_0),
  PUMPKIN_SEEDS(KelpVersion.MC_1_8_0),
  PUMPKIN_STEM(KelpVersion.MC_1_8_0),

  // ARMOR (BOOTS)
  CHAINMAIL_BOOTS(KelpVersion.MC_1_8_0),
  DIAMOND_BOOTS(KelpVersion.MC_1_8_0),
  GOLDEN_BOOTS(KelpVersion.MC_1_8_0),
  IRON_BOOTS(KelpVersion.MC_1_8_0),
  LEATHER_BOOTS(KelpVersion.MC_1_8_0),

  // ARMOR (CHESTPLATE)
  CHAINMAIL_CHESTPLATE(KelpVersion.MC_1_8_0),
  DIAMOND_CHESTPLATE(KelpVersion.MC_1_8_0),
  GOLDEN_CHESTPLATE(KelpVersion.MC_1_8_0),
  IRON_CHESTPLATE(KelpVersion.MC_1_8_0),
  LEATHER_CHESTPLATE(KelpVersion.MC_1_8_0),

  // ARMOR (HELMET)
  CHAINMAIL_HELMET(KelpVersion.MC_1_8_0),
  DIAMOND_HELMET(KelpVersion.MC_1_8_0),
  GOLDEN_HELMET(KelpVersion.MC_1_8_0),
  IRON_HELMET(KelpVersion.MC_1_8_0),
  LEATHER_HELMET(KelpVersion.MC_1_8_0),

  // ARMOR (LEGGINGS)
  CHAINMAIL_LEGGINGS(KelpVersion.MC_1_8_0),
  DIAMOND_LEGGINGS(KelpVersion.MC_1_8_0),
  GOLDEN_LEGGINGS(KelpVersion.MC_1_8_0),
  IRON_LEGGINGS(KelpVersion.MC_1_8_0),
  LEATHER_LEGGINGS(KelpVersion.MC_1_8_0),

  // OTHER
  ACACIA_WOOD(KelpVersion.MC_1_8_0),
  AIR(KelpVersion.MC_1_8_0),
  ALLIUM_FLOWER(KelpVersion.MC_1_8_0),
  ANDESITE(KelpVersion.MC_1_8_0),
  ANVIL(KelpVersion.MC_1_8_0),
  APPLE(KelpVersion.MC_1_8_0),
  ARMOR_STAND(KelpVersion.MC_1_8_0),
  ARROW(KelpVersion.MC_1_8_0),
  AZURE_BLUET(KelpVersion.MC_1_8_0),
  BAKED_POTATO(KelpVersion.MC_1_8_0),
  BAMBOO(KelpVersion.MC_1_14_0),
  BARREL(KelpVersion.MC_1_14_0),
  BARRIER(KelpVersion.MC_1_8_0),
  BEACON(KelpVersion.MC_1_8_0),
  BEDROCK(KelpVersion.MC_1_8_0),
  BEEF(KelpVersion.MC_1_8_0),
  BEEHIVE(KelpVersion.MC_1_15_0),
  BEETROOT(KelpVersion.MC_1_9_0),
  BEETROOTS(KelpVersion.MC_1_9_0),
  BEETROOT_SEEDS(KelpVersion.MC_1_9_0),
  BEETROOT_SOUP(KelpVersion.MC_1_9_0),
  BEE_NEST(KelpVersion.MC_1_15_0),
  BELL(KelpVersion.MC_1_14_0),
  BIRCH_WOOD(KelpVersion.MC_1_8_0),
  BLAST_FURNACE(KelpVersion.MC_1_14_0),
  BLAZE_POWDER(KelpVersion.MC_1_8_0),
  BLAZE_ROD(KelpVersion.MC_1_8_0),
  BLUE_ICE(KelpVersion.MC_1_13_0),
  BLUE_ORCHID(KelpVersion.MC_1_8_0),
  BONE(KelpVersion.MC_1_8_0),
  BONE_BLOCK(KelpVersion.MC_1_10_0),
  BONE_MEAL(KelpVersion.MC_1_8_0),
  BOOK(KelpVersion.MC_1_8_0),
  BOOKSHELF(KelpVersion.MC_1_8_0),
  BOW(KelpVersion.MC_1_8_0),
  BOWL(KelpVersion.MC_1_8_0),
  BREAD(KelpVersion.MC_1_8_0),
  BREWING_STAND(KelpVersion.MC_1_8_0),
  BREWING_STAND_ITEM(KelpVersion.MC_1_8_0),
  BRICK(KelpVersion.MC_1_8_0),
  BRICKS(KelpVersion.MC_1_8_0),
  BROWN_MUSHROOM(KelpVersion.MC_1_8_0),
  BROWN_MUSHROOM_BLOCK(KelpVersion.MC_1_8_0),
  BUBBLE_COLUMN(KelpVersion.MC_1_13_0),
  BUCKET(KelpVersion.MC_1_8_0),
  CACTUS(KelpVersion.MC_1_8_0),
  CAKE(KelpVersion.MC_1_8_0),
  CAKE_ITEM(KelpVersion.MC_1_8_0),
  CAMPFIRE(KelpVersion.MC_1_14_0),
  CARROT(KelpVersion.MC_1_8_0),
  CARROTS(KelpVersion.MC_1_8_0),
  CARROT_ON_A_STICK(KelpVersion.MC_1_8_0),
  CARTOGRAPHY_TABLE(KelpVersion.MC_1_14_0),
  CAULDRON(KelpVersion.MC_1_8_0),
  CAULDRON_ITEM(KelpVersion.MC_1_8_0),
  CAVE_AIR(KelpVersion.MC_1_13_0),
  CHAIN_COMMAND_BLOCK(KelpVersion.MC_1_9_0),
  CHARCOAL(KelpVersion.MC_1_8_0),
  CHEST(KelpVersion.MC_1_8_0),
  CHEST_MINECART(KelpVersion.MC_1_8_0),
  CHICKEN(KelpVersion.MC_1_8_0),
  CHIPPED_ANVIL(KelpVersion.MC_1_8_0),
  CHISELED_QUARTZ_BLOCK(KelpVersion.MC_1_8_0),
  CHISELED_RED_SANDSTONE(KelpVersion.MC_1_8_0),
  CHISELED_SANDSTONE(KelpVersion.MC_1_8_0),
  CHISELED_STONE_BRICKS(KelpVersion.MC_1_8_0),
  CHORUS_FLOWER(KelpVersion.MC_1_9_0),
  CHORUS_FRUIT(KelpVersion.MC_1_9_0),
  CHORUS_PLANT(KelpVersion.MC_1_9_0),
  CLAY(KelpVersion.MC_1_8_0),
  CLAY_BALL(KelpVersion.MC_1_8_0),
  CLOCK(KelpVersion.MC_1_8_0),
  COAL(KelpVersion.MC_1_8_0),
  COAL_BLOCK(KelpVersion.MC_1_8_0),
  COAL_ORE(KelpVersion.MC_1_8_0),
  COARSE_DIRT(KelpVersion.MC_1_8_0),
  COBBLESTONE(KelpVersion.MC_1_8_0),
  COBWEB(KelpVersion.MC_1_8_0),
  COCOA(KelpVersion.MC_1_8_0),
  COCOA_BEANS(KelpVersion.MC_1_8_0),
  COD(KelpVersion.MC_1_13_0),
  COD_BUCKET(KelpVersion.MC_1_13_0),
  COMMAND_BLOCK(KelpVersion.MC_1_8_0),
  COMMAND_BLOCK_MINECART(KelpVersion.MC_1_8_0),
  COMPARATOR(KelpVersion.MC_1_8_0),
  COMPASS(KelpVersion.MC_1_8_0),
  COMPOSTER(KelpVersion.MC_1_14_0),
  CONDUIT(KelpVersion.MC_1_13_0),
  COOKED_BEEF(KelpVersion.MC_1_8_0),
  COOKED_CHICKEN(KelpVersion.MC_1_8_0),
  COOKED_COD(KelpVersion.MC_1_13_0),
  COOKED_MUTTON(KelpVersion.MC_1_8_0),
  COOKED_PORKCHOP(KelpVersion.MC_1_8_0),
  COOKED_RABBIT(KelpVersion.MC_1_8_0),
  COOKED_SALMON(KelpVersion.MC_1_8_0),
  COOKIE(KelpVersion.MC_1_8_0),
  CORNFLOWER(KelpVersion.MC_1_14_0),
  CRACKED_STONE_BRICKS(KelpVersion.MC_1_8_0),
  CRAFTING_TABLE(KelpVersion.MC_1_8_0),
  CROSSBOW(KelpVersion.MC_1_14_0),
  CUT_RED_SANDSTONE(KelpVersion.MC_1_8_0),
  CUT_SANDSTONE(KelpVersion.MC_1_8_0),
  DAMAGED_ANVIL(KelpVersion.MC_1_8_0),
  DANDELION(KelpVersion.MC_1_8_0),
  DARK_OAK_WOOD(KelpVersion.MC_1_8_0),
  DARK_PRISMARINE(KelpVersion.MC_1_8_0),
  DAYLIGHT_DETECTOR(KelpVersion.MC_1_8_0),
  DEAD_BUSH(KelpVersion.MC_1_8_0),
  DEBUG_STICK(KelpVersion.MC_1_13_0),
  DIAMOND(KelpVersion.MC_1_8_0),
  DIAMOND_BLOCK(KelpVersion.MC_1_8_0),
  DIAMOND_HORSE_ARMOR(KelpVersion.MC_1_8_0),
  DIAMOND_ORE(KelpVersion.MC_1_8_0),
  DIORITE(KelpVersion.MC_1_8_0),
  DIRT(KelpVersion.MC_1_8_0),
  DISPENSER(KelpVersion.MC_1_8_0),
  DRAGON_BREATH(KelpVersion.MC_1_9_0),
  DRAGON_EGG(KelpVersion.MC_1_8_0),
  DRIED_KELP(KelpVersion.MC_1_13_0),
  DRIED_KELP_BLOCK(KelpVersion.MC_1_13_0),
  DROPPER(KelpVersion.MC_1_8_0),
  EGG(KelpVersion.MC_1_8_0),
  ELYTRA(KelpVersion.MC_1_9_0),
  EMERALD(KelpVersion.MC_1_8_0),
  EMERALD_BLOCK(KelpVersion.MC_1_8_0),
  EMERALD_ORE(KelpVersion.MC_1_8_0),
  ENCHANTED_BOOK(KelpVersion.MC_1_8_0),
  ENCHANTED_GOLDEN_APPLE(KelpVersion.MC_1_8_0),
  ENCHANTING_TABLE(KelpVersion.MC_1_8_0),
  ENDER_CHEST(KelpVersion.MC_1_8_0),
  ENDER_EYE(KelpVersion.MC_1_8_0),
  ENDER_PEARL(KelpVersion.MC_1_8_0),
  END_CRYSTAL(KelpVersion.MC_1_9_0),
  END_GATEWAY(KelpVersion.MC_1_9_0),
  END_PORTAL(KelpVersion.MC_1_8_0),
  END_PORTAL_FRAME(KelpVersion.MC_1_8_0),
  END_ROD(KelpVersion.MC_1_9_0),
  END_STONE(KelpVersion.MC_1_8_0),
  END_STONE_BRICKS(KelpVersion.MC_1_9_0),
  EXPERIENCE_BOTTLE(KelpVersion.MC_1_8_0),
  FARMLAND(KelpVersion.MC_1_8_0),
  FEATHER(KelpVersion.MC_1_8_0),
  FERMENTED_SPIDER_EYE(KelpVersion.MC_1_8_0),
  FERN(KelpVersion.MC_1_8_0),
  FILLED_MAP(KelpVersion.MC_1_8_0),
  FIRE(KelpVersion.MC_1_8_0),
  FIREWORK_ROCKET(KelpVersion.MC_1_8_0),
  FIREWORK_STAR(KelpVersion.MC_1_8_0),
  FIRE_CHARGE(KelpVersion.MC_1_8_0),
  FISHING_ROD(KelpVersion.MC_1_8_0),
  FLETCHING_TABLE(KelpVersion.MC_1_14_0),
  FLINT(KelpVersion.MC_1_8_0),
  FLINT_AND_STEEL(KelpVersion.MC_1_8_0),
  FLOWER_POT(KelpVersion.MC_1_8_0),
  FLOWER_POT_ITEM(KelpVersion.MC_1_8_0),
  FROSTED_ICE(KelpVersion.MC_1_9_0),
  FURNACE(KelpVersion.MC_1_8_0),
  FURNACE_MINECART(KelpVersion.MC_1_8_0),
  GHAST_TEAR(KelpVersion.MC_1_8_0),
  GLASS_BOTTLE(KelpVersion.MC_1_8_0),
  GLISTERING_MELON_SLICE(KelpVersion.MC_1_8_0),
  GLOWSTONE(KelpVersion.MC_1_8_0),
  GLOWSTONE_DUST(KelpVersion.MC_1_8_0),
  GOLDEN_APPLE(KelpVersion.MC_1_8_0),
  GOLDEN_CARROT(KelpVersion.MC_1_8_0),
  GOLDEN_HORSE_ARMOR(KelpVersion.MC_1_8_0),
  GOLD_BLOCK(KelpVersion.MC_1_8_0),
  GOLD_INGOT(KelpVersion.MC_1_8_0),
  GOLD_NUGGET(KelpVersion.MC_1_8_0),
  GOLD_ORE(KelpVersion.MC_1_8_0),
  GRANITE(KelpVersion.MC_1_8_0),
  GRASS(KelpVersion.MC_1_8_0),
  GRASS_BLOCK(KelpVersion.MC_1_8_0),
  GRASS_PATH(KelpVersion.MC_1_9_0),
  GRAVEL(KelpVersion.MC_1_8_0),
  GRINDSTONE(KelpVersion.MC_1_14_0),
  GUNPOWDER(KelpVersion.MC_1_8_0),
  HAY_BLOCK(KelpVersion.MC_1_8_0),
  HEART_OF_THE_SEA(KelpVersion.MC_1_13_0),
  HONEYCOMB(KelpVersion.MC_1_15_0),
  HONEYCOMB_BLOCK(KelpVersion.MC_1_15_0),
  HONEY_BLOCK(KelpVersion.MC_1_15_0),
  HONEY_BOTTLE(KelpVersion.MC_1_15_0),
  HOPPER(KelpVersion.MC_1_8_0),
  HOPPER_MINECART(KelpVersion.MC_1_8_0),
  ICE(KelpVersion.MC_1_8_0),
  INFESTED_CHISELED_STONE_BRICKS(KelpVersion.MC_1_8_0),
  INFESTED_COBBLESTONE(KelpVersion.MC_1_8_0),
  INFESTED_CRACKED_STONE_BRICKS(KelpVersion.MC_1_8_0),
  INFESTED_MOSSY_STONE_BRICKS(KelpVersion.MC_1_8_0),
  INFESTED_STONE(KelpVersion.MC_1_8_0),
  INFESTED_STONE_BRICKS(KelpVersion.MC_1_8_0),
  INK_SAC(KelpVersion.MC_1_8_0),
  IRON_BARS(KelpVersion.MC_1_8_0),
  IRON_BLOCK(KelpVersion.MC_1_8_0),
  IRON_HORSE_ARMOR(KelpVersion.MC_1_8_0),
  IRON_INGOT(KelpVersion.MC_1_8_0),
  IRON_NUGGET(KelpVersion.MC_1_11_1),
  IRON_ORE(KelpVersion.MC_1_8_0),
  ITEM_FRAME(KelpVersion.MC_1_8_0),
  JACK_O_LANTERN(KelpVersion.MC_1_8_0),
  JIGSAW(KelpVersion.MC_1_14_0),
  JUKEBOX(KelpVersion.MC_1_8_0),
  JUNGLE_WOOD(KelpVersion.MC_1_8_0),
  KELP(KelpVersion.MC_1_13_0),
  KELP_PLANT(KelpVersion.MC_1_13_0),
  KNOWLEDGE_BOOK(KelpVersion.MC_1_12_0),
  LADDER(KelpVersion.MC_1_8_0),
  LANTERN(KelpVersion.MC_1_14_0),
  LAPIS_BLOCK(KelpVersion.MC_1_8_0),
  LAPIS_LAZULI(KelpVersion.MC_1_8_0),
  LAPIS_ORE(KelpVersion.MC_1_8_0),
  LARGE_FERN(KelpVersion.MC_1_8_0),
  LAVA(KelpVersion.MC_1_8_0),
  LAVA_BUCKET(KelpVersion.MC_1_8_0),
  LEAD(KelpVersion.MC_1_8_0),
  LEATHER(KelpVersion.MC_1_8_0),
  LEATHER_HORSE_ARMOR(KelpVersion.MC_1_14_0),
  LECTERN(KelpVersion.MC_1_14_0),
  LEVER(KelpVersion.MC_1_8_0),
  LILAC(KelpVersion.MC_1_8_0),
  LILY_OF_THE_VALLEY(KelpVersion.MC_1_14_0),
  LILY_PAD(KelpVersion.MC_1_8_0),
  LOOM(KelpVersion.MC_1_14_0),
  MAGMA_BLOCK(KelpVersion.MC_1_10_0),
  MAGMA_CREAM(KelpVersion.MC_1_8_0),
  MAP(KelpVersion.MC_1_8_0),
  MILK_BUCKET(KelpVersion.MC_1_8_0),
  MINECART(KelpVersion.MC_1_8_0),
  MOSSY_COBBLESTONE(KelpVersion.MC_1_8_0),
  MOSSY_STONE_BRICKS(KelpVersion.MC_1_8_0),
  MOVING_PISTON(KelpVersion.MC_1_8_0),
  MUSHROOM_STEM(KelpVersion.MC_1_8_0),
  MUSHROOM_STEW(KelpVersion.MC_1_8_0),
  MUSIC_DISC_11(KelpVersion.MC_1_8_0),
  MUSIC_DISC_13(KelpVersion.MC_1_8_0),
  MUSIC_DISC_BLOCKS(KelpVersion.MC_1_8_0),
  MUSIC_DISC_CAT(KelpVersion.MC_1_8_0),
  MUSIC_DISC_CHIRP(KelpVersion.MC_1_8_0),
  MUSIC_DISC_FAR(KelpVersion.MC_1_8_0),
  MUSIC_DISC_MALL(KelpVersion.MC_1_8_0),
  MUSIC_DISC_MELLOHI(KelpVersion.MC_1_8_0),
  MUSIC_DISC_STAL(KelpVersion.MC_1_8_0),
  MUSIC_DISC_STRAD(KelpVersion.MC_1_8_0),
  MUSIC_DISC_WAIT(KelpVersion.MC_1_8_0),
  MUSIC_DISC_WARD(KelpVersion.MC_1_8_0),
  MUTTON(KelpVersion.MC_1_8_0),
  MYCELIUM(KelpVersion.MC_1_8_0),
  NAME_TAG(KelpVersion.MC_1_8_0),
  NAUTILUS_SHELL(KelpVersion.MC_1_13_0),
  NETHERRACK(KelpVersion.MC_1_8_0),
  NETHER_BRICK(KelpVersion.MC_1_8_0),
  NETHER_BRICKS(KelpVersion.MC_1_8_0),
  NETHER_PORTAL(KelpVersion.MC_1_8_0),
  NETHER_QUARTZ_ORE(KelpVersion.MC_1_8_0),
  NETHER_STAR(KelpVersion.MC_1_8_0),
  NETHER_WART(KelpVersion.MC_1_8_0),
  NETHER_WART_BLOCK(KelpVersion.MC_1_10_0),
  NOTE_BLOCK(KelpVersion.MC_1_8_0),
  OAK_WOOD(KelpVersion.MC_1_8_0),
  OBSERVER(KelpVersion.MC_1_11_0),
  OBSIDIAN(KelpVersion.MC_1_8_0),
  ORANGE_TULIP(KelpVersion.MC_1_8_0),
  OXEYE_DAISY(KelpVersion.MC_1_8_0),
  PACKED_ICE(KelpVersion.MC_1_8_0),
  PAINTING(KelpVersion.MC_1_8_0),
  PAPER(KelpVersion.MC_1_8_0),
  PEONY(KelpVersion.MC_1_8_0),
  PHANTOM_MEMBRANE(KelpVersion.MC_1_13_0),
  PINK_TULIP(KelpVersion.MC_1_8_0),
  PISTON(KelpVersion.MC_1_8_0),
  PISTON_HEAD(KelpVersion.MC_1_8_0),
  PODZOL(KelpVersion.MC_1_8_0),
  POISONOUS_POTATO(KelpVersion.MC_1_8_0),
  POLISHED_ANDESITE(KelpVersion.MC_1_8_0),
  POLISHED_DIORITE(KelpVersion.MC_1_8_0),
  POLISHED_GRANITE(KelpVersion.MC_1_8_0),
  POPPED_CHORUS_FRUIT(KelpVersion.MC_1_9_0),
  POPPY(KelpVersion.MC_1_8_0),
  PORKCHOP(KelpVersion.MC_1_8_0),
  POTATO(KelpVersion.MC_1_8_0),
  POTATOES(KelpVersion.MC_1_8_0),
  POTTED_ALLIUM(KelpVersion.MC_1_8_0),
  POTTED_AZURE_BLUET(KelpVersion.MC_1_8_0),
  POTTED_BAMBOO(KelpVersion.MC_1_14_0),
  POTTED_BLUE_ORCHID(KelpVersion.MC_1_8_0),
  POTTED_BROWN_MUSHROOM(KelpVersion.MC_1_8_0),
  POTTED_CACTUS(KelpVersion.MC_1_8_0),
  POTTED_CORNFLOWER(KelpVersion.MC_1_14_0),
  POTTED_DANDELION(KelpVersion.MC_1_8_0),
  POTTED_DEAD_BUSH(KelpVersion.MC_1_8_0),
  POTTED_FERN(KelpVersion.MC_1_8_0),
  POTTED_LILY_OF_THE_VALLEY(KelpVersion.MC_1_14_0),
  POTTED_ORANGE_TULIP(KelpVersion.MC_1_8_0),
  POTTED_OXEYE_DAISY(KelpVersion.MC_1_8_0),
  POTTED_PINK_TULIP(KelpVersion.MC_1_8_0),
  POTTED_POPPY(KelpVersion.MC_1_8_0),
  POTTED_RED_MUSHROOM(KelpVersion.MC_1_8_0),
  POTTED_RED_TULIP(KelpVersion.MC_1_8_0),
  POTTED_WHITE_TULIP(KelpVersion.MC_1_8_0),
  POTTED_WITHER_ROSE(KelpVersion.MC_1_14_0),
  PRISMARINE(KelpVersion.MC_1_8_0),
  PRISMARINE_BRICKS(KelpVersion.MC_1_8_0),
  PRISMARINE_CRYSTALS(KelpVersion.MC_1_8_0),
  PRISMARINE_SHARD(KelpVersion.MC_1_8_0),
  PUFFERFISH(KelpVersion.MC_1_8_0),
  PUFFERFISH_BUCKET(KelpVersion.MC_1_13_0),
  PURPUR_BLOCK(KelpVersion.MC_1_9_0),
  PURPUR_PILLAR(KelpVersion.MC_1_9_0),
  QUARTZ(KelpVersion.MC_1_8_0),
  QUARTZ_BLOCK(KelpVersion.MC_1_8_0),
  QUARTZ_PILLAR(KelpVersion.MC_1_8_0),
  RABBIT(KelpVersion.MC_1_8_0),
  RABBIT_FOOT(KelpVersion.MC_1_8_0),
  RABBIT_HIDE(KelpVersion.MC_1_8_0),
  RABBIT_STEW(KelpVersion.MC_1_8_0),
  REDSTONE(KelpVersion.MC_1_8_0),
  REDSTONE_BLOCK(KelpVersion.MC_1_8_0),
  REDSTONE_LAMP(KelpVersion.MC_1_8_0),
  REDSTONE_ORE(KelpVersion.MC_1_8_0),
  REDSTONE_TORCH(KelpVersion.MC_1_8_0),
  REDSTONE_WALL_TORCH(KelpVersion.MC_1_8_0),
  REDSTONE_WIRE(KelpVersion.MC_1_8_0),
  RED_MUSHROOM(KelpVersion.MC_1_8_0),
  RED_MUSHROOM_BLOCK(KelpVersion.MC_1_8_0),
  RED_NETHER_BRICKS(KelpVersion.MC_1_10_0),
  RED_SAND(KelpVersion.MC_1_8_0),
  RED_SANDSTONE(KelpVersion.MC_1_8_0),
  RED_TULIP(KelpVersion.MC_1_8_0),
  REPEATER(KelpVersion.MC_1_8_0),
  REPEATING_COMMAND_BLOCK(KelpVersion.MC_1_9_0),
  ROSE_BUSH(KelpVersion.MC_1_8_0),
  ROTTEN_FLESH(KelpVersion.MC_1_8_0),
  SADDLE(KelpVersion.MC_1_8_0),
  SALMON(KelpVersion.MC_1_8_0),
  SALMON_BUCKET(KelpVersion.MC_1_13_0),
  SAND(KelpVersion.MC_1_8_0),
  SANDSTONE(KelpVersion.MC_1_8_0),
  SCAFFOLDING(KelpVersion.MC_1_14_0),
  SCUTE(KelpVersion.MC_1_13_0),
  SEAGRASS(KelpVersion.MC_1_13_0),
  SEA_LANTERN(KelpVersion.MC_1_8_0),
  SEA_PICKLE(KelpVersion.MC_1_13_0),
  SHEARS(KelpVersion.MC_1_8_0),
  SHIELD(KelpVersion.MC_1_9_0),
  SHULKER_SHELL(KelpVersion.MC_1_11_0),
  SLIME_BALL(KelpVersion.MC_1_8_0),
  SLIME_BLOCK(KelpVersion.MC_1_8_0),
  SMITHING_TABLE(KelpVersion.MC_1_14_0),
  SMOKER(KelpVersion.MC_1_14_0),
  SMOOTH_QUARTZ(KelpVersion.MC_1_14_0),
  SMOOTH_RED_SANDSTONE(KelpVersion.MC_1_14_0),
  SMOOTH_SANDSTONE(KelpVersion.MC_1_14_0),
  SMOOTH_STONE(KelpVersion.MC_1_8_0),
  SNOW(KelpVersion.MC_1_8_0),
  SNOWBALL(KelpVersion.MC_1_8_0),
  SNOW_BLOCK(KelpVersion.MC_1_8_0),
  SOUL_SAND(KelpVersion.MC_1_8_0),
  SPAWNER(KelpVersion.MC_1_8_0),
  SPECTRAL_ARROW(KelpVersion.MC_1_9_0),
  SPIDER_EYE(KelpVersion.MC_1_8_0),
  SPONGE(KelpVersion.MC_1_8_0),
  SPRUCE_WOOD(KelpVersion.MC_1_8_0),
  STICK(KelpVersion.MC_1_8_0),
  STICKY_PISTON(KelpVersion.MC_1_8_0),
  STONE(KelpVersion.MC_1_8_0),
  STONECUTTER(KelpVersion.MC_1_14_0),
  STONE_BRICKS(KelpVersion.MC_1_8_0),
  STRING(KelpVersion.MC_1_8_0),
  STRUCTURE_BLOCK(KelpVersion.MC_1_9_0),
  STRUCTURE_VOID(KelpVersion.MC_1_10_0),
  SUGAR(KelpVersion.MC_1_8_0),
  SUGAR_CANE(KelpVersion.MC_1_8_0),
  SUGAR_CANE_BLOCK(KelpVersion.MC_1_8_0),
  SUNFLOWER(KelpVersion.MC_1_8_0),
  SUSPICIOUS_STEW(KelpVersion.MC_1_14_0),
  SWEET_BERRIES(KelpVersion.MC_1_14_0),
  SWEET_BERRY_BUSH(KelpVersion.MC_1_14_0),
  TALL_GRASS(KelpVersion.MC_1_8_0),
  TALL_SEAGRASS(KelpVersion.MC_1_8_0),
  TIPPED_ARROW(KelpVersion.MC_1_9_0),
  TNT(KelpVersion.MC_1_8_0),
  TNT_MINECART(KelpVersion.MC_1_8_0),
  TORCH(KelpVersion.MC_1_8_0),
  TOTEM_OF_UNDYING(KelpVersion.MC_1_11_0),
  TRAPPED_CHEST(KelpVersion.MC_1_8_0),
  TRIDENT(KelpVersion.MC_1_13_0),
  TRIPWIRE(KelpVersion.MC_1_8_0),
  TRIPWIRE_HOOK(KelpVersion.MC_1_8_0),
  TROPICAL_FISH(KelpVersion.MC_1_13_0),
  TROPICAL_FISH_BUCKET(KelpVersion.MC_1_13_0),
  TURTLE_EGG(KelpVersion.MC_1_13_0),
  TURTLE_HELMET(KelpVersion.MC_1_13_0),
  VINE(KelpVersion.MC_1_8_0),
  VOID_AIR(KelpVersion.MC_1_13_0),
  WALL_TORCH(KelpVersion.MC_1_8_0),
  WATER(KelpVersion.MC_1_8_0),
  WATER_BUCKET(KelpVersion.MC_1_8_0),
  WET_SPONGE(KelpVersion.MC_1_8_0),
  WHEAT(KelpVersion.MC_1_8_0),
  WHEAT_SEEDS(KelpVersion.MC_1_8_0),
  WHITE_TULIP(KelpVersion.MC_1_8_0),
  WITHER_ROSE(KelpVersion.MC_1_14_0),
  WRITABLE_BOOK(KelpVersion.MC_1_8_0),
  WRITTEN_BOOK(KelpVersion.MC_1_8_0),
  ;

  private KelpVersion since;

  KelpMaterial(KelpVersion since) {
    this.since = since;
  }

  public KelpVersion since() {
    return since;
  }

  /**
   * Returns a collection of materials included in newer versions than
   * the given one. So if you input 1.12 for example, only materials
   * added in 1.13 will be returned.
   *
   * @param version The version you want to use for the calculation.
   * @return The final collection
   */
  public static Collection<KelpMaterial> aboveVersion(KelpVersion version) {
    Collection<KelpMaterial> output = new ArrayList<>();

    if (version == KelpVersion.highestVersion()) {
      return output;
    }

    for (KelpMaterial material : KelpMaterial.values()) {
      if (material.since() == version) continue;
      if (KelpVersion.higherVersion(version,  material.since()) == material.since()) {
        output.add(material);
      }
    }

    return output;
  }

  /**
   * Returns a collection of materials added in older versions than
   * the given one. If you input 1.11 for example, only materials
   * contained in 1.10 will be returned.
   *
   * @param version The version
   * @return The final collection.
   */
  public static Collection<KelpMaterial> belowVersion(KelpVersion version) {
    Collection<KelpMaterial> output = new ArrayList<>();

    if (version == KelpVersion.lowestVersion()) {
      return output;
    }

    for (KelpMaterial material : KelpMaterial.values()) {
      if (material.since() == version) continue;
      if (KelpVersion.lowerVersion(version,  material.since()) == material.since()) {
        output.add(material);
      }
    }

    return output;
  }

  /**
   * Returns a collection of materials which have been added in the
   * given version. No materials of older or future versions are included.
   *
   * @param version The version you want to get the materials of.
   * @return A collection of newly added materials.
   */
  public static Collection<KelpMaterial> matchesVersion(KelpVersion version) {
    Collection<KelpMaterial> output = new ArrayList<>();

    for (KelpMaterial material : KelpMaterial.values()) {
      if (material.since() == version) {
        output.add(material);
      }
    }

    return output;
  }

  /**
   * Returns a collection of materials available in the given
   * kelp version.
   *
   * @param version The version you want to check the materials of.
   * @return The collection of materials included in the given version.
   */
  public static Collection<KelpMaterial> includedIn(KelpVersion version) {
    Collection<KelpMaterial> output = new ArrayList<>(belowVersion(version));
    output.addAll(matchesVersion(version));
    return output;
  }

  @Override
  public String toString() {
    return super.toString();
  }
}
